logging:
  level:
    sql:  debug

spring:
  jpa:
    show_sql: true
    database: H2
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE

pokeapi.pokemon.resources.path: https://pokeapi.co/api/v2/pokemon/
